"""Offener Recherche-Snapshot vom 8. August 2026.

Bewertungen sind vorläufige Kodierungen, keine Tatsachen über ein Medium. Nur der
DLF-Kommentar wurde im Volltext geprüft; übrige Einträge kennzeichnen ihren Status.

Jedes Medium trägt seit dem 8. August 2026 ein Feld ``evidence`` mit belegbaren
Einordnungsgründen. Die Belege dokumentieren die *Grundlage* der politischen
Arbeitshypothese – Trägerschaft/Eigentümer, Rechtsrahmen, Selbstverständnis,
externe Einordnung und Publikumsstudien –, nicht einen automatischen Nachweis
einer Schlagseite im Einzelartikel. Ein belastbarer Richtungsbefund entsteht erst
aus dem geprüften Artikelkorpus (siehe ``METHODE.md`` und ``article_codings``).
Jeder Beleg nennt Art, Aussage, Quelle und URL, damit er nachprüfbar bleibt.
"""

# Wiederkehrende, überprüfbare Standardquellen für die Einordnung.
_DNR = ("Reuters Institute Digital News Report 2025 – Ergebnisse für Deutschland "
        "(Leibniz-Institut für Medienforschung / Hans-Bredow-Institut)")
_DNR_URL = "https://leibniz-hbi.de/en/hbi-publications/reuters-institute-digital-news-report-2025-findings-for-germany/"
_MOM = "Media Ownership Monitor Germany (Reporter ohne Grenzen)"
_MOM_URL = "https://germany.mom-gmr.org/"
_MSTV = "Medienstaatsvertrag (MStV), Auftrag und Staatsferne des öffentlich-rechtlichen Rundfunks"
_MSTV_URL = "https://www.die-medienanstalten.de/service/rechtsgrundlagen"

MEDIA = [
    {"name":"taz", "domain":"taz.de", "profile":"links/progressiv", "profile_note":"Vorläufige redaktionelle Einordnung; nicht auf jeden Einzeltext übertragbar.",
     "evidence":[
        {"art":"Trägerschaft","beleg":"Die taz erscheint bei der taz Verlags- und Vertriebs GmbH und wird von der taz Genossenschaft (über 22.000 Genossinnen und Genossen) getragen; sie ist selbstverwaltet und nicht renditeorientiert.","quelle":"taz Panter Stiftung / taz Genossenschaft","url":"https://taz.de/Genossenschaft/!p4350/"},
        {"art":"Selbstverständnis/Herkunft","beleg":"1978/79 aus der links-alternativen Bewegung gegründet; versteht sich als linke, gesellschaftskritische Tageszeitung. Publikum in Publikumsstudien am weitesten links verortet.","quelle":_DNR,"url":_DNR_URL}]},
    {"name":"BILD", "domain":"bild.de", "profile":"rechts/populär-konservativ", "profile_note":"Boulevardmedium; Profil und Darstellungsform getrennt bewerten.",
     "evidence":[
        {"art":"Eigentümer","beleg":"BILD gehört zur Axel Springer SE; auflagen- und reichweitenstärkstes Boulevardmedium Deutschlands.","quelle":_MOM,"url":_MOM_URL},
        {"art":"Politische Agenda des Eigentümers","beleg":"Axel Springer verpflichtet seine Redaktionen auf verbindliche Unternehmensgrundsätze ('Essentials'): u. a. Eintreten für die transatlantische Bindung an die USA, für das Existenzrecht Israels, für die freie Marktwirtschaft und die europäische Einigung sowie Ablehnung von politischem und religiösem Extremismus. Mitarbeitende unterzeichnen diese mit dem Arbeitsvertrag.","quelle":"Axel Springer SE – Unternehmensgrundsätze (Essentials)","url":"https://www.axelspringer.com/de/unternehmensgrundsaetze"},
        {"art":"Publikumsverortung","beleg":"Publikum im Digital News Report tendenziell rechts der Mitte; boulevardeske, zuspitzende Darstellungsform.","quelle":_DNR,"url":_DNR_URL}]},
    {"name":"WELT", "domain":"welt.de", "profile":"liberal-konservativ/rechts der Mitte", "profile_note":"Vorläufige redaktionelle Einordnung; Einzelartikel können abweichen.",
     "evidence":[
        {"art":"Eigentümer","beleg":"WELT gehört zur Axel Springer SE; überregionale Tageszeitung und Nachrichtensender.","quelle":_MOM,"url":_MOM_URL},
        {"art":"Politische Agenda des Eigentümers","beleg":"Wie BILD unterliegt WELT den verbindlichen Axel-Springer-Grundsätzen ('Essentials'): transatlantische Bindung, Existenzrecht Israels, freie Marktwirtschaft, europäische Einigung, Ablehnung von Extremismus – von allen Redaktionen zu unterzeichnen.","quelle":"Axel Springer SE – Unternehmensgrundsätze (Essentials)","url":"https://www.axelspringer.com/de/unternehmensgrundsaetze"},
        {"art":"Publikumsverortung","beleg":"Meinungsstarke liberal-konservative Linie; Publikum im Digital News Report rechts der Mitte verortet.","quelle":_DNR,"url":_DNR_URL}]},
    {"name":"Süddeutsche Zeitung", "domain":"sueddeutsche.de", "profile":"liberal/links der Mitte", "profile_note":"Vorläufige redaktionelle Einordnung; Einzelartikel können abweichen.",
     "evidence":[
        {"art":"Eigentümer","beleg":"Die SZ gehört zur Südwestdeutschen Medienholding (SWMH); größte überregionale Abonnement-Tageszeitung.","quelle":_MOM,"url":_MOM_URL},
        {"art":"Publikumsverortung","beleg":"Linksliberales Profil; Publikum im Digital News Report links der Mitte.","quelle":_DNR,"url":_DNR_URL}]},
    {"name":"FOCUS", "domain":"focus.de", "profile":"bürgerlich/konservativ der Mitte", "profile_note":"Vorläufig; Nachrichtenagenturtexte gesondert kennzeichnen.",
     "evidence":[
        {"art":"Eigentümer","beleg":"FOCUS erscheint bei Hubert Burda Media (BurdaVerlag); bürgerlich-konservatives Nachrichtenmagazin.","quelle":_MOM,"url":_MOM_URL},
        {"art":"Hinweis","beleg":"Online-Angebot übernimmt viele dpa-/Agenturtexte; redaktionelle Eigenleistung und Agenturmaterial müssen getrennt bewertet werden.","quelle":"eigene Kodierung, siehe article_codings","url":_MOM_URL}]},
    {"name":"DER SPIEGEL", "domain":"spiegel.de", "profile":"liberal/links der Mitte", "profile_note":"Nachricht, Analyse und Meinung müssen getrennt verglichen werden.",
     "evidence":[
        {"art":"Trägerschaft","beleg":"Herausgegeben von der Spiegel-Gruppe; Mitarbeiterinnen und Mitarbeiter halten über die Mitarbeiter-KG eine Sperrminorität, weitere Anteile bei Gruner+Jahr/Bertelsmann und den Augstein-Erben.","quelle":_MOM,"url":_MOM_URL},
        {"art":"Publikumsverortung","beleg":"Linksliberales Profil mit starkem Investigativteil; Publikum im Digital News Report links der Mitte.","quelle":_DNR,"url":_DNR_URL}]},
    {"name":"Badische Zeitung", "domain":"badische-zeitung.de", "profile":"regional/liberale Mitte", "profile_note":"Nur grobe Arbeitshypothese; für eine belastbare Einstufung Korpus nötig.",
     "evidence":[
        {"art":"Eigentümer","beleg":"Regionale Abonnement-Tageszeitung des Badischen Verlags (Freiburg) für Südbaden; überregionale Themen häufig über Agentur/Kooperation.","quelle":_MOM,"url":_MOM_URL}]},
    {"name":"Berliner Zeitung", "domain":"berliner-zeitung.de", "profile":"heterogen/gesellschaftspolitisch schwer einzuordnen", "profile_note":"Keine eindimensionale Links-rechts-Zuordnung ohne Korpus.",
     "evidence":[
        {"art":"Eigentümer","beleg":"Seit 2019 gehört der Berliner Verlag den Unternehmern Holger und Silke Friedrich; die redaktionelle Linie gilt seither als heterogen und kontrovers diskutiert.","quelle":_MOM,"url":_MOM_URL}]},
    {"name":"FAZ", "domain":"faz.net", "profile":"liberal-konservativ", "profile_note":"Vorläufige redaktionelle Einordnung; Einzelartikel können abweichen.",
     "evidence":[
        {"art":"Trägerschaft","beleg":"Die Frankfurter Allgemeine Zeitung GmbH gehört zu 93,7 Prozent der gemeinnützigen FAZIT-Stiftung; die Herausgeber bestimmen maßgeblich die publizistische Linie und sichern die Unabhängigkeit.","quelle":"FAZIT-Stiftung / Media Ownership Monitor","url":"https://www.fazit-stiftung.de/fazit-stiftung/historie"},
        {"art":"Selbstverständnis","beleg":"Erklärtes liberal-konservatives Profil mit ausführlichen Analysen und meinungsstarken Leitartikeln.","quelle":_MOM,"url":"https://germany.mom-gmr.org/de/media/print/outlet/frankfurter-allgemeine-zeitung-115710/"}]},
    {"name":"Tagesspiegel", "domain":"tagesspiegel.de", "profile":"liberal/progressiv", "profile_note":"Vorläufige Einordnung; Nachrichten, Interviews und Analysen werden getrennt ausgewertet.",
     "evidence":[
        {"art":"Eigentümer","beleg":"Der Tagesspiegel gehört zu Dieter von Holtzbrinck Medien (DvH Medien); überregional wirksame Berliner Abonnement-Zeitung.","quelle":_MOM,"url":_MOM_URL}]},
    {"name":"tagesschau.de", "domain":"tagesschau.de", "profile":"öffentlich-rechtlich; nachrichtenorientiert", "profile_note":"Nachrichten, FAQ und Einordnungen werden getrennt bewertet; Quellenattribution bleibt sichtbar.",
     "evidence":[
        {"art":"Rechtsrahmen","beleg":"tagesschau.de wird von ARD-aktuell (Redaktion beim NDR) verantwortet; öffentlich-rechtlicher Auftrag mit Gebot der Ausgewogenheit und Staatsferne.","quelle":_MSTV,"url":_MSTV_URL},
        {"art":"Vertrauen/Nutzung","beleg":"Öffentlich-rechtliche Nachrichten werden im Digital News Report über politische Lager hinweg am meisten genutzt und genießen das höchste Vertrauen.","quelle":_DNR,"url":_DNR_URL}]},
    {"name":"stern", "domain":"stern.de", "profile":"liberal/gesellschaftspolitisch", "profile_note":"Vorläufige Einordnung; Magazin- und Nachrichtenformate getrennt prüfen.",
     "evidence":[
        {"art":"Eigentümer","beleg":"Der stern gehört zu RTL Deutschland (Bertelsmann), zuvor Gruner + Jahr; gesellschaftspolitisches Magazin mit liberaler Grundhaltung.","quelle":_MOM,"url":_MOM_URL}]},
    {"name":"BR", "domain":"br.de", "profile":"öffentlich-rechtlich; regional", "profile_note":"Regionaler öffentlich-rechtlicher Anbieter; Nachrichten und Kommentare getrennt prüfen.",
     "evidence":[
        {"art":"Rechtsrahmen","beleg":"Bayerischer Rundfunk, Anstalt des öffentlichen Rechts nach dem Bayerischen Rundfunkgesetz; ARD-Mitglied mit öffentlich-rechtlichem Auftrag und Staatsferne.","quelle":_MSTV,"url":_MSTV_URL}]},
    {"name":"WDR", "domain":"wdr.de", "profile":"öffentlich-rechtlich; regional", "profile_note":"Regionaler öffentlich-rechtlicher Anbieter; Nachrichten, Reportagen und Kommentare getrennt prüfen.",
     "evidence":[
        {"art":"Rechtsrahmen","beleg":"Westdeutscher Rundfunk, Anstalt des öffentlichen Rechts nach dem WDR-Gesetz; größte ARD-Anstalt mit öffentlich-rechtlichem Auftrag.","quelle":_MSTV,"url":_MSTV_URL}]},
    {"name":"MDR", "domain":"mdr.de", "profile":"öffentlich-rechtlich; regional", "profile_note":"Regionaler öffentlich-rechtlicher Anbieter; Daten- und Politikbeiträge getrennt prüfen.",
     "evidence":[
        {"art":"Rechtsrahmen","beleg":"Mitteldeutscher Rundfunk, Anstalt des öffentlichen Rechts nach dem MDR-Staatsvertrag (Sachsen, Sachsen-Anhalt, Thüringen).","quelle":_MSTV,"url":_MSTV_URL}]},
    {"name":"RBB", "domain":"rbb24.de", "profile":"öffentlich-rechtlich; regional", "profile_note":"Regionaler öffentlich-rechtlicher Anbieter; Berlin/Brandenburg-Kontext separat ausweisen.",
     "evidence":[
        {"art":"Rechtsrahmen","beleg":"Rundfunk Berlin-Brandenburg, Anstalt des öffentlichen Rechts nach dem rbb-Staatsvertrag der Länder Berlin und Brandenburg.","quelle":_MSTV,"url":_MSTV_URL}]},
    {"name":"ZDF", "domain":"zdf.de", "profile":"öffentlich-rechtlich; bundesweit", "profile_note":"Nachrichten und Magazine getrennt prüfen; Quellenattribution und Aktualisierungen dokumentieren.",
     "evidence":[
        {"art":"Rechtsrahmen","beleg":"Zweites Deutsches Fernsehen, gemeinnützige Anstalt des öffentlichen Rechts nach dem ZDF-Staatsvertrag; bundesweiter öffentlich-rechtlicher Auftrag.","quelle":_MSTV,"url":_MSTV_URL},
        {"art":"Vertrauen/Nutzung","beleg":"Zählt mit der ARD im Digital News Report zu den meistgenutzten und vertrauenswürdigsten Nachrichtenmarken.","quelle":_DNR,"url":_DNR_URL}]},
    {"name":"SWR", "domain":"swr.de", "profile":"öffentlich-rechtlich; regional", "profile_note":"Regionaler öffentlich-rechtlicher Anbieter; die Einordnung ist eine Arbeitshypothese.",
     "evidence":[
        {"art":"Rechtsrahmen","beleg":"Südwestrundfunk, Anstalt des öffentlichen Rechts nach dem SWR-Staatsvertrag (Baden-Württemberg, Rheinland-Pfalz).","quelle":_MSTV,"url":_MSTV_URL}]},
    {"name":"Pro Asyl", "domain":"proasyl.de", "profile":"NGO/Interessenvertretung", "profile_note":"Keine Zeitung: Positionen und Faktenchecks werden als Interessenvertretungsquelle separat ausgewertet.",
     "evidence":[
        {"art":"Trägerschaft/Zweck","beleg":"PRO ASYL ist der Förderverein PRO ASYL e. V., eine Menschenrechts- und Flüchtlingsschutzorganisation; sie tritt satzungsgemäß für die Rechte Geflüchteter ein und ist damit erklärte Interessenvertretung, kein neutrales Nachrichtenmedium.","quelle":"PRO ASYL – Über uns","url":"https://www.proasyl.de/ueber-uns/"}]},
    {"name":"Deutschlandfunk", "domain":"deutschlandfunk.de", "profile":"öffentlich-rechtlich; Mitte bis liberal", "profile_note":"Auftrag und Finanzierung sind keine politische Bewertung; Kommentar separat behandeln.",
     "evidence":[
        {"art":"Rechtsrahmen","beleg":"Deutschlandfunk ist Programm von Deutschlandradio, einer gemeinschaftlich von ARD und ZDF getragenen Körperschaft des öffentlichen Rechts nach dem Deutschlandradio-Staatsvertrag; wortlastiges Informationsprogramm mit öffentlich-rechtlichem Auftrag.","quelle":_MSTV,"url":_MSTV_URL}]},
    {"name":"NDR", "domain":"ndr.de", "profile":"öffentlich-rechtlich; regional", "profile_note":"Auftrag und Finanzierung sind keine politische Bewertung; Nachrichten und Kommentare getrennt prüfen.",
     "evidence":[
        {"art":"Rechtsrahmen","beleg":"Norddeutscher Rundfunk, Anstalt des öffentlichen Rechts nach dem NDR-Staatsvertrag (Hamburg, Niedersachsen, Schleswig-Holstein, Mecklenburg-Vorpommern); verantwortet u. a. ARD-aktuell.","quelle":_MSTV,"url":_MSTV_URL}]},
    {"name":"NIUS", "domain":"nius.de", "profile":"rechts/konservativ-populistisch", "profile_note":"Vorläufige redaktionelle Einordnung; Befund benötigt Artikelkorpus.",
     "evidence":[
        {"art":"Eigentümer/Finanzierung","beleg":"NIUS (Start Juli 2023) wird von der Vius SE & Co. KGaA betrieben; Chefredakteur ist Julian Reichelt, Hauptfinanzier der Unternehmer Frank Gotthardt. NIUS bezeichnet sich als 'Stimme der Mehrheit'.","quelle":"Wikipedia: Nius / Media Ownership Monitor (Frank Gotthardt)","url":"https://de.wikipedia.org/wiki/Nius"},
        {"art":"Politische Agenda des Eigentümers","beleg":"Frank Gotthardt (CompuGroup-Gründer) gilt als CDU-nah: Er und seine Frau spendeten im Januar 2025 rund 180.000 Euro an die CDU und 200.000 Euro an die FDP; Gotthardt ist Ehrenvorsitzender des Wirtschaftsrats der CDU Rheinland-Pfalz (formal parteiunabhängige, CDU-nahe Lobbyorganisation) und finanziert neben NIUS auch das österreichische Portal 'exxpress'.","quelle":"LobbyControl / CORRECTIV","url":"https://www.lobbycontrol.de/aus-der-lobbywelt/zu-grosse-naehe-julia-kloeckner-und-der-mann-hinter-nius-122188/"},
        {"art":"Externe Einordnung","beleg":"Wird in Medienberichterstattung überwiegend als rechtspopulistisches, meinungsstark zuspitzendes Portal beschrieben.","quelle":"Media Ownership Monitor Germany","url":"https://germany.mom-gmr.org/de/owners/individual-owners/owner/frank-gotthardt-115044/"}]},
    {"name":"Apollo News", "domain":"apollo-news.net", "profile":"rechts/libertär-konservativ", "profile_note":"Vorläufige redaktionelle Einordnung; Befund benötigt Artikelkorpus.",
     "evidence":[
        {"art":"Herausgeber","beleg":"Apollo News wird von der Apollo Medien GmbH (Berlin) unter Max Mannhart herausgegeben; junges Online-Magazin mit erklärt rechtslibertärem Selbstverständnis ('Magazin für die Freiheit').","quelle":"Wikipedia: Apollo News","url":"https://de.wikipedia.org/wiki/Apollo_News"},
        {"art":"Externe Einordnung","beleg":"Wird von Beobachtungsstellen (u. a. CeMAS, Amadeu Antonio Stiftung) als rechtslibertär bis rechtskonservativ eingeordnet.","quelle":"CeMAS / Amadeu Antonio Stiftung","url":"https://www.amadeu-antonio-stiftung.de/apollo-news-das-journalistische-vorfeld-152069/"}]},
    {"name":"Die ZEIT", "domain":"zeit.de", "profile":"liberal/meinungsplural", "profile_note":"Wochenzeitung mit ausgeprägter Debattenkultur; Pro-/Contra-Formate und Ressorts getrennt bewerten.",
     "evidence":[
        {"art":"Eigentümer","beleg":"Die ZEIT erscheint im Zeitverlag Gerd Bucerius; Gesellschafter sind Dieter von Holtzbrinck Medien und die Verlagsgruppe Georg von Holtzbrinck. Liberales, meinungsplurales Wochenmedium.","quelle":_MOM,"url":_MOM_URL}]},
    {"name":"Handelsblatt", "domain":"handelsblatt.com", "profile":"wirtschaftsliberal", "profile_note":"Wirtschafts- und Finanztageszeitung; ordnungspolitische Kommentierung von Nachricht trennen.",
     "evidence":[
        {"art":"Eigentümer","beleg":"Das Handelsblatt gehört zur Handelsblatt Media Group (Dieter von Holtzbrinck Medien); führende deutsche Wirtschaftstageszeitung mit marktwirtschaftlich-ordnungspolitischer Grundhaltung.","quelle":_MOM,"url":_MOM_URL}]},
    {"name":"RND (Redaktionsnetzwerk Deutschland)", "domain":"rnd.de", "profile":"liberal/links der Mitte; parteinahe Eigentümerbeteiligung dokumentiert", "profile_note":"Zentralredaktion für viele Regionalzeitungen; die SPD-Beteiligung ist ein Struktur-, kein Inhaltsbeweis.",
     "evidence":[
        {"art":"Eigentümer/Beteiligung","beleg":"Das RND ist die überregionale Zentralredaktion der Madsack Mediengruppe und beliefert über 60 Tageszeitungen. Größte Einzelgesellschafterin von Madsack ist mit 23,1 Prozent die SPD-eigene Deutsche Druck- und Verlagsgesellschaft (DDVG).","quelle":"Wikipedia: Verlagsgesellschaft Madsack / Media Ownership Monitor (SPD/DDVG)","url":"https://de.wikipedia.org/wiki/Verlagsgesellschaft_Madsack"},
        {"art":"Einordnungshinweis","beleg":"Die Eigentümerbeteiligung einer Partei begründet für sich noch keine redaktionelle Schlagseite; sie ist als Transparenz- und Prüfhinweis dokumentiert, nicht als Beweis.","quelle":"Media Ownership Monitor (SPD)","url":"https://germany.mom-gmr.org/de/owners/individual-owners/owner/social-democratic-party-of-germany-112228/"}]},
    {"name":"n-tv", "domain":"n-tv.de", "profile":"nachrichtenorientiert/wirtschaftsnah", "profile_note":"Privater Nachrichtensender; überwiegend nachrichtlich, Agenturanteil beachten.",
     "evidence":[
        {"art":"Eigentümer","beleg":"n-tv gehört zu RTL Deutschland (Bertelsmann); privater Nachrichten- und Wirtschaftssender.","quelle":_MOM,"url":_MOM_URL}]},
    {"name":"t-online", "domain":"t-online.de", "profile":"reichweitenstark/nachrichtlich-boulevardnah", "profile_note":"Großes Nachrichtenportal; nachrichtliche und meinungsbetont-zugespitzte Stücke getrennt prüfen.",
     "evidence":[
        {"art":"Eigentümer","beleg":"t-online wird von der Ströer-Gruppe (Ströer Content Group) betrieben; eines der reichweitenstärksten deutschen Nachrichtenportale.","quelle":_MOM,"url":_MOM_URL}]},
    {"name":"Junge Freiheit", "domain":"jungefreiheit.de", "profile":"neurechts/rechtskonservativ", "profile_note":"Erklärt konservativ-rechte Wochenzeitung; Nachricht, Kommentar und Positionierung streng trennen.",
     "evidence":[
        {"art":"Herausgeber/Ausrichtung","beleg":"Wochenzeitung des JF-Verlags (Chefredakteur/Herausgeber Dieter Stein); versteht sich als konservativ-rechtes Blatt und wird in der Forschung dem neurechten Spektrum zugeordnet.","quelle":"Media Ownership Monitor Germany","url":_MOM_URL}]},
    {"name":"junge Welt", "domain":"jungewelt.de", "profile":"marxistisch/links; vom Verfassungsschutz als linksextrem geführt", "profile_note":"Erklärt marxistische Tageszeitung; Ausrichtung ist transparent, Einordnung als Struktur-, nicht Inhaltsurteil pro Artikel.",
     "evidence":[
        {"art":"Trägerschaft/Ausrichtung","beleg":"Die junge Welt erscheint im Verlag 8. Mai GmbH und wird genossenschaftlich (LPG junge Welt) getragen; sie versteht sich ausdrücklich als marxistisch orientierte linke Tageszeitung.","quelle":"junge Welt / Verlag 8. Mai","url":"https://www.jungewelt.de/verlag/"},
        {"art":"Externe Einordnung","beleg":"Als einzige deutschsprachige Tageszeitung wird die junge Welt in Verfassungsschutzberichten als linksextrem geführt; das VG Berlin bestätigte 2024 diese Nennung. Die Redaktion sieht Marxismus als bloßen Kompass der Gesellschaftskritik.","quelle":"Legal Tribune Online / VG Berlin 2024","url":"https://www.lto.de/recht/hintergruende/h/verassungsschutzbericht-verfassungsschutz-junge-welt-pressefreiheit"}]},
    {"name":"nd (nd.DerTag)", "domain":"nd-aktuell.de", "profile":"links/sozialistisch", "profile_note":"Aus dem SED-Zentralorgan 'Neues Deutschland' hervorgegangen, heute genossenschaftlich; erklärt linke Ausrichtung.",
     "evidence":[
        {"art":"Trägerschaft/Herkunft","beleg":"'nd' (früher 'Neues Deutschland', bis 1989 SED-Zentralorgan) wird heute von der genossenschaftlichen nd.Genossenschaft eG getragen und versteht sich als linke, sozialistische Tageszeitung.","quelle":"Media Ownership Monitor Germany","url":_MOM_URL}]},
    {"name":"Cicero", "domain":"cicero.de", "profile":"liberal-konservativ/meinungsbetont", "profile_note":"Meinungsmagazin für politische Kultur; Essays und Kommentare dominieren gegenüber Nachricht.",
     "evidence":[
        {"art":"Eigentümer/Charakter","beleg":"Cicero erscheint im Res Publica Verlag (Weimer Media Group); Meinungsmagazin mit überwiegend liberal-konservativer, debattenorientierter Ausrichtung.","quelle":_MOM,"url":_MOM_URL}]},
    {"name":"Frankfurter Rundschau", "domain":"fr.de", "profile":"linksliberal", "profile_note":"Traditionell linksliberale Zeitung; heute innerhalb der FAZ-Verlagsgruppe. Ausrichtung ohne Korpus nur grob.",
     "evidence":[
        {"art":"Eigentümer/Herkunft","beleg":"Die Frankfurter Rundschau gilt traditionell als linksliberale überregionale Zeitung; nach der Insolvenz 2012/13 wird sie innerhalb der Verlagsgruppe der Frankfurter Allgemeinen herausgegeben.","quelle":"Media Ownership Monitor Germany","url":_MOM_URL}]},
]

ARTICLES = [
    {"medium":"Deutschlandfunk","title":"Wahn, überall Wahn","url":"https://www.deutschlandfunk.de/ceuta-spanien-eu-asylpolitik-migration-abschottung-kommentar-100.html","published":"2026-08-08","genre":"Kommentar","access_status":"Volltext","research_status":"vollständig geprüft","summary":"Kritisiert die Reaktionen von 22 EU-Staaten und fordert legale Wege sowie Ursachenbekämpfung.","framing":"Wahn; Migrationshysterie; Klassenkeile; Marschformation; Abschottung","orientation_signal":"stark migrationsliberal; Gegner überwiegend abwertend gerahmt","confidence":0.95,"source_note":"Primärseite und vollständiger Artikeltext geprüft."},
    {"medium":"BILD","title":"Ceuta: Migranten überrennen spanische Hafenstadt","url":"https://www.bild.de/suche.bild.html?query=Ceuta","published":"2026-07-30","genre":"Bericht","access_status":"Metadaten","research_status":"Titel/Index geprüft","summary":"Titel betont Kontrollverlust und Massenzustrom.","framing":"überrennen","orientation_signal":"restriktives Sicherheits-/Kontrollframe","confidence":0.45,"source_note":"Google-News-Titel gefunden; Volltext noch nicht belastbar geprüft."},
    {"medium":"WELT","title":"Ceuta: Grenze praktisch zusammengebrochen – Spanische Regierung entsendet Armee","url":"https://www.welt.de/politik/ausland/article6a6b4d80b5b26399f0be14ec/ceuta-grenze-praktisch-zusammengebrochen-spanische-regierung-entsendet-armee.html","published":"2026-07-31","genre":"Bericht","access_status":"teilweise/Paywall möglich","research_status":"Metadaten geprüft","summary":"Betont Grenzzusammenbruch und militärische Reaktion.","framing":"praktisch zusammengebrochen; Ansturm","orientation_signal":"Sicherheits- und Kontrollframe","confidence":0.55,"source_note":"Direktlink und Suchindex geprüft; Volltextprüfung ausstehend."},
    {"medium":"WELT","title":"Notdienst und NGO schätzen Zahl der Migranten in Ceuta noch immer auf bis zu 7000","url":"https://www.welt.de/suche/?q=Ceuta%207000","published":"2026-08-06","genre":"Bericht","access_status":"Metadaten","research_status":"Titel/Index geprüft","summary":"Stellt amtlicher Rückkehrdarstellung eine abweichende Schätzung gegenüber.","framing":"Diskrepanz amtliche Angabe vs. Schätzung","orientation_signal":"regierungskritisches Kontrollframe","confidence":0.55,"source_note":"Im Google-News-Index WELT, nicht Apollo News, zugeordnet."},
    {"medium":"Süddeutsche Zeitung","title":"Wurden die Migranten nach Ceuta geschickt?","url":"https://www.sueddeutsche.de/politik/migrantenansturm-ceuta-spanien-marokko-ursachen-folgen-li.3525203","published":"2026-08","genre":"Analyse","access_status":"teilweise/Paywall möglich","research_status":"Metadaten geprüft","summary":"Untersucht mögliche Steuerung, Rückkehr und politische Ursachen.","framing":"Migrantenansturm; Ursachenfrage","orientation_signal":"geopolitisches Erklärungsframe","confidence":0.5,"source_note":"Direktlink und Suchindex geprüft; Volltextprüfung ausstehend."},
    {"medium":"Süddeutsche Zeitung","title":"Laut Madrid: Nahezu alle Migranten haben Ceuta verlassen","url":"https://www.sueddeutsche.de/suche?search=Ceuta","published":"2026-07-31","genre":"Meldung","access_status":"Metadaten","research_status":"Titel/Index geprüft","summary":"Gibt die amtliche Darstellung mit Attribution 'Laut Madrid' wieder.","framing":"amtliche Angabe ausdrücklich attribuiert","orientation_signal":"nicht bestimmbar","confidence":0.35,"source_note":"Google-News-Index; keine unabhängige Bestätigung im Titel."},
    {"medium":"DER SPIEGEL","title":"Ceuta: Spanien sucht nach den Gründen für den Grenzsturm","url":"https://www.spiegel.de/thema/ceuta/","published":"2026-07-31","genre":"Analyse","access_status":"Paywall","research_status":"Titel/Index geprüft","summary":"Fokus auf Ursachen und spanische Reaktion.","framing":"Grenzsturm","orientation_signal":"gemischtes Ursachen-/Kontrollframe","confidence":0.4,"source_note":"Themenindex; mehrere Spiegel-Beiträge vorhanden."},
    {"medium":"DER SPIEGEL","title":"Diesen Mangel an Solidarität werden die Spanier nicht vergessen","url":"https://www.spiegel.de/suche/?suchbegriff=Ceuta%20Solidarit%C3%A4t","published":"2026-08-01","genre":"Kommentar","access_status":"Paywall","research_status":"Titel/Index geprüft","summary":"Kritisiert mangelnde europäische Solidarität mit Spanien.","framing":"Mangel an Solidarität","orientation_signal":"spanienfreundlich/migrationsliberal","confidence":0.5,"source_note":"Als Meinung gekennzeichnet; Volltextprüfung ausstehend."},
    {"medium":"FAZ","title":"Ceuta: Fast 50.000 Migranten kehren freiwillig nach Marokko zurück","url":"https://www.faz.net/suche/?query=Ceuta","published":"2026-07-31","genre":"Meldung","access_status":"Metadaten","research_status":"Titel/Index geprüft","summary":"Berichtet Rückkehrzahl und bezeichnet die Rückkehr als freiwillig.","framing":"freiwillige Rückkehr","orientation_signal":"nicht bestimmbar","confidence":0.35,"source_note":"Google-News-Index; Quelle der Zahl im Volltext zu prüfen."},
    {"medium":"taz","title":"Kein aktueller Ceuta-Beitrag im geprüften Index gefunden","url":"https://taz.de/!s=Ceuta/","published":"","genre":"Recherchestatus","access_status":"Suche","research_status":"nicht gefunden","summary":"Bis zum Stichtag kein eindeutig zuordenbarer aktueller Treffer.","framing":"","orientation_signal":"keine Bewertung möglich","confidence":0.0,"source_note":"Nichtberichterstattung ist kein politischer Befund."},
    {"medium":"FOCUS","title":"Kein belastbar zuordenbarer aktueller Ceuta-Beitrag gefunden","url":"https://www.focus.de/","published":"","genre":"Recherchestatus","access_status":"Suche","research_status":"nicht gefunden","summary":"Bis zum Stichtag kein belastbarer Treffer.","framing":"","orientation_signal":"keine Bewertung möglich","confidence":0.0,"source_note":"Die frühere interne Such-URL liefert 404; Suche muss über News-Index und Website wiederholt werden."},
    {"medium":"Badische Zeitung","title":"Kein belastbar zuordenbarer aktueller Ceuta-Beitrag gefunden","url":"https://www.badische-zeitung.de/suche?query=Ceuta","published":"","genre":"Recherchestatus","access_status":"Suche","research_status":"nicht gefunden","summary":"Bis zum Stichtag kein belastbarer Treffer.","framing":"","orientation_signal":"keine Bewertung möglich","confidence":0.0,"source_note":"Regionale Agenturübernahmen können nachträglich erscheinen."},
    {"medium":"Berliner Zeitung","title":"Kein belastbar zuordenbarer aktueller Ceuta-Beitrag gefunden","url":"https://www.berliner-zeitung.de/search?query=Ceuta","published":"","genre":"Recherchestatus","access_status":"Suche","research_status":"nicht gefunden","summary":"Bis zum Stichtag kein belastbarer Treffer.","framing":"","orientation_signal":"keine Bewertung möglich","confidence":0.0,"source_note":"Suche muss später wiederholt werden."},
    {"medium":"NIUS","title":"Kein aktueller Ceuta-Beitrag im geprüften News-Index gefunden","url":"https://www.nius.de/suche?q=Ceuta","published":"","genre":"Recherchestatus","access_status":"Suche","research_status":"nicht gefunden","summary":"Bis zum Stichtag kein belastbarer Treffer.","framing":"","orientation_signal":"keine Bewertung möglich","confidence":0.0,"source_note":"NIUS ist nicht mit Euronews/niusnews.com zu verwechseln."},
    {"medium":"Apollo News","title":"Kein Beleg für den zugeschriebenen 7000-Bericht gefunden","url":"https://apollo-news.net/?s=Ceuta","published":"","genre":"Recherchestatus","access_status":"Suche","research_status":"nicht gefunden","summary":"Die auffindbare 7000-Meldung stammt im News-Index von WELT.","framing":"","orientation_signal":"keine Bewertung möglich","confidence":0.0,"source_note":"Zuschreibung an Apollo News derzeit nicht bestätigt."},
]

CLAIMS = [
    {"id":1,"claim":"Nahezu alle Ceuta-Migranten seien nach Marokko zurückgekehrt.","status":"teilweise belegt / zeitgebundene Behördenangabe","assessment":"Madrid meldete mehr als 48.000 Rückkehrer. Bei 60.000 bis 70.000 Angekommenen folgt daraus nicht ohne Weiteres 'nahezu alle'. Spätere Schätzungen nennen bis zu 7.000 weiterhin in Ceuta.","supporting_sources":["Spanisches Innenministerium, zitiert von DLF am 31.07.2026","SZ/FAZ/WELT-Meldungen vom 31.07./01.08."],"contradicting_sources":["WELT: Notdienst und NGO schätzen bis zu 7.000, 06.08.2026"],"checked_at":"2026-08-08"},
    {"id":2,"claim":"7.000 Menschen seien noch in Ceuta und bekämen nun Asylverfahren.","status":"teilweise belegt, zweiter Teil offen","assessment":"Eine Schätzung von Notdienst und NGO von bis zu 7.000 ist auffindbar. Dass alle 7.000 Asylverfahren erhalten, ist durch die bisher gefundenen Quellen nicht belegt.","supporting_sources":["WELT-Titel im Google-News-Index, 06.08.2026"],"contradicting_sources":["Keine belastbare Primärquelle für pauschale 7.000 Asylverfahren gefunden"],"checked_at":"2026-08-08"},
    {"id":3,"claim":"Unter den Ceuta-Migranten seien nachgewiesen Dschihadisten gewesen.","status":"derzeit nicht belegt / widersprüchliche Berichte","assessment":"Auffindbar sind Berichte über Prüfungen möglicher Verbindungen. Eine spätere Meldung zitiert das spanische Innenministerium mit dem Ergebnis, es seien keine Dschihadisten festgestellt worden. 'Nachgewiesen' ist daher derzeit nicht haltbar.","supporting_sources":["Berichte über eingeleitete Sicherheitsprüfungen"],"contradicting_sources":["Euronews: Spanisches Innenministerium – keine Dschihadisten, 05.08.2026"],"checked_at":"2026-08-08"},
    {"id":4,"claim":"Der spanische Oberste Gerichtshof habe unmittelbare Zurückweisungen von über den Wasserweg nach Ceuta gelangten Migranten verboten.","status":"im Kern belegt, Formulierung präzisieren","assessment":"Der Tribunal Supremo entschied am 08.07.2026, dass die Sonderregel der 'devolución en caliente' nicht auf Personen angewandt werden kann, die Ceuta oder Melilla schwimmend erreichen, ohne ein physisches Rückhalteelement zu überwinden. Das ist kein dauerhaftes Bleiberecht: Es schließt die sofortige formlose Zurückweisung aus, nicht eine spätere Rückführung nach individuellem Verfahren. Die pauschale Erweiterung auf jeden denkbaren Wasserweg oder jedes Boot geht über den bislang belegten Urteilskern hinaus.","supporting_sources":["EFE, 08.07.2026: El Supremo confirma que no se puede aplicar la devolución en caliente a migrantes que llegan por mar","El País, 08.07.2026: El Supremo prohíbe las devoluciones en caliente de quienes intentan entrar a nado","El Mundo, 08.07.2026: Einreise schwimmend aktiviert die Sonderregel nicht","Juristische Einordnungen bei Legal Today und Confilegal, 10./30.07.2026"],"contradicting_sources":["Kein Beleg dafür, dass das Urteil ein dauerhaftes Aufenthaltsrecht gewährt","Anwendungsbereich hängt nach den Berichten von der Überwindung eines physischen Rückhalteelements ab"],"checked_at":"2026-08-08"},
    {"id":5,"claim":"Das Urteil habe über Social-Media-Falschmeldungen die Massenmigration nach Ceuta ausgelöst.","status":"Wirkungskette teilweise belegt, Monokausalität offen","assessment":"Spanische Medien und Faktenchecker dokumentieren, dass das Urteil in Marokko als angebliche Grenzöffnung beziehungsweise dauerhaftes Bleiberecht verkürzt verbreitet wurde. Das stützt einen Anreizeffekt. Dass diese Desinformation allein die Krise verursachte, ist nicht bewiesen; Grenzüberwachung, marokkanische Politik, Schlepper und soziale Lage sind konkurrierende oder zusätzliche Faktoren.","supporting_sources":["Maldita.es, 06.08.2026: Verbreitung der Grenzöffnungsbotschaft auf Facebook in Marokko","LaSexta, 31.07.2026: Sánchez spricht von interessierter Lesart durch Schleuser","La Vanguardia und weitere spanische Medien nennen das Urteil als Faktor"],"contradicting_sources":["Mehrere alternative Ursachen werden berichtet","Zeitliche Abfolge allein beweist keine alleinige Kausalität"],"checked_at":"2026-08-08"},
    {"id":6,"claim":"Zurückweisungen von Menschen mit Asylgesuch an deutschen Binnengrenzen seien generell eindeutig illegal.","status":"zu pauschal; konkreter Verfahrensverstoß gerichtlich bejaht","assessment":"Das VG Berlin entschied am 02.06.2025 in drei Eilverfahren, dass die konkreten Zurückweisungen somalischer Antragsteller nach Polen rechtswidrig waren, weil nach dem Asylgesuch zunächst das Dublin-Verfahren durchzuführen gewesen wäre. Die Beschlüsse entschieden konkrete Fälle im Eilverfahren, nicht abstrakt jede denkbare Zurückweisung. Die Bundesregierung berief sich unter anderem auf Art. 72 AEUV; das Gericht sah dessen Voraussetzungen im konkreten Vortrag nicht als ausreichend dargelegt an.","supporting_sources":["VG Berlin, drei Eilbeschlüsse vom 02.06.2025","Dublin-III-Verordnung, insbesondere Zuständigkeitsverfahren","Juristische Einordnung Legal Tribune Online, 02./06.06.2025"],"contradicting_sources":["Bundesregierung vertrat eine weitergehende nationale Befugnis unter Berufung auf Art. 72 AEUV","Keine abstrakte Normenkontrolle und keine Entscheidung des EuGH oder Bundesverwaltungsgerichts in diesen drei Eilverfahren"],"checked_at":"2026-08-08"},
    {"id":7,"claim":"Das VG Berlin sei unzuständig gewesen, weil Berlin nicht an der Grenze liegt.","status":"unbelegt; Gerichtsstand folgt nicht einfach dem Grenzort","assessment":"Verwaltungsgerichtliche Zuständigkeit richtet sich nach VwGO und asylrechtlichen Sonderregeln, nicht allein danach, wo eine Grenzkontrolle stattfand. Die bloße Entfernung Berlins von der deutsch-polnischen Grenze beweist keine Unzuständigkeit. Für einen belastbaren Vorwurf müssen Rubrum und Zuständigkeitsbegründung der Beschlüsse ausgewertet werden.","supporting_sources":["Verwaltungsgerichtsordnung § 52","Die Verfahren wurden vom VG Berlin angenommen und entschieden"],"contradicting_sources":["Vollständige Beschlussgründe zur konkreten örtlichen Zuständigkeit sind noch in die Datenbank zu übernehmen"],"checked_at":"2026-08-08"},
    {"id":8,"claim":"Pro Asyl habe die Grenzklage organisiert und einem politisch grünen Richter zugeleitet.","status":"teilweise/offen; Richtervorwurf nicht belegt","assessment":"Eine Unterstützung der Antragsteller durch Flüchtlingsrechtsorganisationen ist öffentlich berichtet und als solche rechtmäßig. Ein Kläger kann ein zuständiges Gericht nicht frei nach gewünschtem Richter auswählen; die kammerinterne Verteilung folgt dem Geschäftsverteilungsplan. Für Parteizugehörigkeit, Befangenheit oder gezielte Zuleitung des entscheidenden Richters liegt bislang kein belastbarer Nachweis vor.","supporting_sources":["Öffentliche Berichte über Unterstützung der drei somalischen Antragsteller","Gerichtlicher Geschäftsverteilungsplan als Zuweisungsmechanismus"],"contradicting_sources":["Keine belastbare Quelle für die behauptete grüne Parteizugehörigkeit oder manipulierte Zuteilung gefunden"],"checked_at":"2026-08-08"},
    {"id":9,"claim":"Die Ampel habe jedem endgültig abgelehnten Asylbewerber auf Steuerkosten einen zusätzlichen Pflichtanwalt gegeben.","status":"irreführend","assessment":"Der frühere § 62d AufenthG verpflichtete das Gericht, Personen in Abschiebungshaft oder Ausreisegewahrsam für die Dauer des Freiheitsentziehungsverfahrens einen anwaltlichen Vertreter zu bestellen. Das galt nicht pauschal für jedes abgeschlossene Asylverfahren und nicht als zusätzliche komplette Asylklage. Die Norm wurde im Rückführungsverbesserungsgesetz der Ampel eingeführt und ist in der aktuellen Fassung wieder weggefallen.","supporting_sources":["Historischer § 62d AufenthG","Bundestagsmaterialien zum Rückführungsverbesserungsgesetz","Aktuelle amtliche Fassung: § 62d weggefallen"],"contradicting_sources":["Die Bezeichnung 'Pflichtanwalt für jeden abgelehnten Asylbewerber' überdehnt Personenkreis und Verfahrensumfang"],"checked_at":"2026-08-08"},
    {"id":10,"claim":"Medien hätten beim tödlichen U-Bahn-Fall in Hamburg verschwiegen, dass der Täter aus dem Südsudan über ein Flüchtlingsprogramm aufgenommen worden war.","status":"als Pauschalaussage widerlegt; Zeitvergleich erforderlich","assessment":"Der 25-jährige Südsudanese riss Ende Januar 2026 am U-Bahnhof Wandsbek Markt eine 18-jährige Iranerin vor eine einfahrende Bahn und starb ebenfalls. NDR, FAZ, Focus, Bild und Welt berichteten später ausdrücklich über Herkunft, Flüchtlingsprogramm und teils vorherige Polizeikontakte. Offen bleibt für jedes Medium einzeln, welche Angaben bereits in der Erstmeldung verfügbar waren, wann aktualisiert wurde und ob trotz gesicherter Information dauerhaft relevanter Kontext fehlte.","supporting_sources":["NDR, 02.02.2026: 'Er kam über ein Flüchtlingsprogramm und war der Polizei schon bekannt'","FAZ, 02.02.2026: Täter kam über Flüchtlingsprogramm","Focus, 03.02.2026: Aufnahme über die UN","Bild und Welt, 30.01.–01.02.2026: Herkunft beziehungsweise Vorwissen"],"contradicting_sources":["Frühe Kurzmeldungen können Details noch nicht enthalten haben","Bewusstes Verschweigen erfordert Nachweis, dass die Redaktion gesicherte relevante Information kannte"],"checked_at":"2026-08-08"},
    {"id":11,"claim":"Die Täter der Gruppenvergewaltigung am Hans-Bunte-Areal in Freiburg hätten auffällig milde Strafen erhalten.","status":"Tatsachenbasis belegt; 'mild' ist eine zu begründende Wertung","assessment":"Am 23.07.2020 wurden zehn von elf Angeklagten verurteilt: Bei sieben stellte das LG Freiburg Vergewaltigung fest, bei einem einen sonstigen sexuellen Übergriff, zwei wurden wegen unterlassener Hilfeleistung verurteilt. Acht erhielten Freiheits- beziehungsweise Jugendstrafen, zwei Jugendstrafen auf Bewährung; ein Angeklagter wurde hinsichtlich des Tatgeschehens freigesprochen. Der Hauptverurteilte erhielt 5 Jahre 6 Monate, ein weiterer 4 Jahre 3 Monate, der deutsche Verurteilte 4 Jahre. Der BGH machte die Urteile 2021 rechtskräftig. Ob dies 'mild' war, muss anhand Tatbeitrag, Jugendstrafrecht, gesetzlichem Strafrahmen und Urteilsgründen bewertet werden, nicht nur anhand der Gruppentat insgesamt.","supporting_sources":["LG Freiburg, Urteil vom 23.07.2020","BGH, Beschluss vom 16.06.2021 – 1 StR 81/21","Tagesschau und regionale Prozessberichte"],"contradicting_sources":["Nicht alle elf Angeklagten wurden wegen Vergewaltigung verurteilt","Individuelle Strafen beziehen sich auf nachgewiesene Tatbeiträge; Jugendstrafrecht verfolgt zusätzlich Erziehungsgedanken"],"checked_at":"2026-08-08"},
    {"id":12,"claim":"In Velbert hätten acht Rumänen nach einem Schwimmbadbesuch ein 13-jähriges Mädchen gruppenvergewaltigt.","status":"Tatkern belegt, Nationalität falsch und Tatbeiträge differenzieren","assessment":"Die Tat vom 21.04.2018 und die Beteiligung einer Gruppe von insgesamt acht Jugendlichen sind belegt. Nach den auffindbaren Gerichts- und Medienquellen stammten sie jedoch aus Bulgarien, nicht Rumänien. Im ersten Verfahren standen sechs Jugendliche vor Gericht: Drei wurden wegen Vergewaltigung, drei wegen Beihilfe verurteilt; zwei erhielten Bewährungsstrafen. Zwei weitere Jugendliche hatten sich nach Bulgarien abgesetzt und wurden für ein gesondertes Verfahren festgenommen. Die Formulierung, alle acht hätten selbst vergewaltigt, übergeht unterschiedliche Tatbeiträge.","supporting_sources":["LG Wuppertal, Pressemitteilungen 13/2018 und 16/2018","BILD, WELT, SZ und n-tv vom 08.10.2018"],"contradicting_sources":["Keine belastbare Quelle für rumänische Staatsangehörigkeit","Gericht unterschied Vergewaltigung und Beihilfe"],"checked_at":"2026-08-08"},
    {"id":13,"claim":"In Nürnberg seien Grooming-Gangs nach britischem Muster aus Syrern, Pakistanern und Nordafrikanern nachgewiesen.","status":"Ermittlungskomplex und mehrere Herkunftsangaben belegt; Gangstruktur und Verurteilungen offen","assessment":"Die Polizei gründete die EKO Kajal wegen Hinweisen auf Sexualdelikte gegen Mädchen und junge Frauen sowie die Abgabe von Drogen und Medikamenten an Minderjährige. Bis 07.07.2026 saßen zehn Tatverdächtige in Untersuchungshaft. Amtlich genannt wurden bei verschiedenen Verdächtigen unter anderem syrische und pakistanische Staatsangehörigkeiten sowie ein Staatenloser. Das belegt ernsthafte Ermittlungen und macht ein pauschales Verschweigen der Herkunft unzutreffend. Untersuchungshaft ist jedoch keine Verurteilung; eine einheitlich organisierte Grooming-Gang nach britischem Muster und die pauschale Kategorie Nordafrikaner sind durch die vorliegenden Polizeimeldungen nicht als Gesamtbefund nachgewiesen.","supporting_sources":["Polizeipräsidium Mittelfranken, Meldung 492 vom 21.05.2026","Polizeipräsidium Mittelfranken, Meldung 628 vom 07.07.2026"],"contradicting_sources":["Die Polizei spricht von einer Ermittlungskommission und einem Deliktszusammenhang, nicht von einer rechtskräftig festgestellten organisierten Gang","Ermittlungen und Haftbefehle ersetzen keine Verurteilungen"],"checked_at":"2026-08-08"},
]

FACTS = [
    {"id":1,"topic":"Kriminalität und Staatsangehörigkeit","statement":"Die Tatverdächtigenbelastungszahl nichtdeutscher Personen liegt bei Gewaltkriminalität laut BKA 2025 ungefähr viermal so hoch wie bei deutschen Personen.","value":"ca. Faktor 4","scope":"Deutschland, Gewaltkriminalität, PKS 2025","source_name":"Bundeskriminalamt – PKS 2025","source_url":"https://www.bka.de/DE/AktuelleInformationen/StatistikenLagebilder/PolizeilicheKriminalstatistik/PKS2025/Polizeiliche_Kriminalstatistik_2025/Polizeiliche_Kriminalstatistik_2025_node.html","limitations":"Tatverdächtige sind nicht Verurteilte. Die Kategorie nichtdeutsch ist sehr heterogen; Alters- und Geschlechtsstruktur sowie Anzeige- und Kontrollunterschiede beeinflussen Vergleiche.","checked_at":"2026-08-08"},
    {"id":2,"topic":"Statistische Definition","statement":"Die TVBZ zählt ermittelte ansässige Tatverdächtige je 100.000 Personen des entsprechenden Bevölkerungsanteils; Kinder unter acht Jahren werden ausgeschlossen.","value":"je 100.000","scope":"Definition PKS 2025","source_name":"Bundeskriminalamt – PKS 2025","source_url":"https://www.bka.de/DE/AktuelleInformationen/StatistikenLagebilder/PolizeilicheKriminalstatistik/PKS2025/Polizeiliche_Kriminalstatistik_2025/Polizeiliche_Kriminalstatistik_2025_node.html","limitations":"Nichtansässige Tatverdächtige dürfen nicht durch die Wohnbevölkerung geteilt werden. Rohe Fallanteile sind keine Belastungszahlen.","checked_at":"2026-08-08"},
    {"id":3,"topic":"Staatsangehörigkeit vs. Migrationshintergrund","statement":"Eingebürgerte Personen werden in der PKS als deutsche Staatsangehörige geführt; die Standard-PKS erlaubt deshalb keine vollständige Auswertung nach Migrationshintergrund.","value":"unterschiedliche Kategorien","scope":"Deutschland, PKS-Systematik","source_name":"Bundeskriminalamt – PKS Methodik","source_url":"https://www.bka.de/DE/AktuelleInformationen/StatistikenLagebilder/PolizeilicheKriminalstatistik/pks_node.html","limitations":"Aus Name, Aussehen oder Geburtsort darf kein Migrationshintergrund abgeleitet werden. Zusätzliche Länderstatistiken können andere Merkmale erfassen.","checked_at":"2026-08-08"},
    {"id":4,"topic":"Marokkanische Staatsangehörige","statement":"Eine konkrete Überrepräsentationsquote wird erst ausgegeben, wenn Tatverdächtigenzahl, ansässige Vergleichsbevölkerung, Deliktsbereich, Alter, Geschlecht und Zeitraum kompatibel vorliegen.","value":"noch offen","scope":"Deutschland, gewünschte Sonderauswertung","source_name":"Methodischer Prüfvermerk","source_url":"https://www.bka.de/DE/AktuelleInformationen/StatistikenLagebilder/PolizeilicheKriminalstatistik/pks_node.html","limitations":"Die pauschale Aussage 'Marokkaner sind extrem überrepräsentiert' ist ohne Delikt, Nenner und Kontrollvariablen zu ungenau.","checked_at":"2026-08-08"},
    {"id":5,"topic":"Deutsche Grenzzurückweisungen","statement":"Das VG Berlin beanstandete am 02.06.2025 drei konkrete Zurückweisungen somalischer Asylsuchender nach Polen, weil vor einer Zurückweisung das Dublin-Verfahren erforderlich gewesen sei.","value":"3 Eilbeschlüsse","scope":"konkrete Einzelfälle; vorläufiger Rechtsschutz","source_name":"Legal Tribune Online – Einordnung der VG-Beschlüsse","source_url":"https://www.lto.de/recht/hintergruende/h/vg-berlin-zurueckweisung-grenze-asyl-dublin-beschluesse-mythen","limitations":"Eilentscheidungen eines erstinstanzlichen Gerichts sind keine abstrakte Entscheidung über jede Grenzkonstellation.","checked_at":"2026-08-08"},
    {"id":6,"topic":"Rechtsbeistand bei Freiheitsentziehung","statement":"Der frühere § 62d AufenthG betraf die Bestellung eines Rechtsanwalts für Menschen in Abschiebungshaft oder Ausreisegewahrsam und nur für die Dauer dieses Verfahrens.","value":"§ 62d AufenthG, inzwischen weggefallen","scope":"Abschiebungshaft/Ausreisegewahrsam, nicht gesamtes Asylverfahren","source_name":"Gesetze im Internet – aktuelle Fassung","source_url":"https://www.gesetze-im-internet.de/aufenthg_2004/__62d.html","limitations":"Für die politische Urheberschaft sind Änderungsantrag, Ausschussfassung und Abstimmung getrennt auszuwerten.","checked_at":"2026-08-08"},
    {"id":7,"topic":"Afghanistan-Aufnahmeprogramme","statement":"Eine bestandskräftige, nicht widerrufene Aufnahmezusage band die Bundesrepublik im konkreten Fall VG 8 L 290/25 V; Identität war geklärt und Sicherheitsbedenken waren nicht ersichtlich.","value":"VG Berlin, 07.07.2025","scope":"konkreter Eilfall mit erfüllten weiteren Visumvoraussetzungen","source_name":"Verwaltungsgericht Berlin – Pressemitteilung 34/2025","source_url":"https://www.berlin.de/gerichte/verwaltungsgericht/presse/pressemitteilungen/2025/pressemitteilung.1578126.php","limitations":"Die Entscheidung erlaubte weiterhin das Beenden des Programms und das Aussetzen neuer Zusagen; sie ist nicht auf Fälle mit offenen Sicherheitsfragen übertragbar.","checked_at":"2026-08-08"},
    {"id":8,"topic":"Afghanistan-Aufnahmeprogramme","statement":"Eine Aufnahmezusage allein ersetzt weder persönliche Vorsprache noch Identitäts- und Sicherheitsprüfung.","value":"OVG 6 S 51/25","scope":"vierköpfige Familie mit noch nicht abgeschlossener Sicherheitsprüfung","source_name":"OVG Berlin-Brandenburg – Pressemitteilung 30/25","source_url":"https://www.berlin.de/gerichte/oberverwaltungsgericht/presse/pressemitteilungen/2025/pressemitteilung.1593408.php","limitations":"Anderer Sachverhalt als VG 8 L 290/25 V; beide Entscheidungen dürfen nicht als direkter Widerspruch ohne Fallunterschied dargestellt werden.","checked_at":"2026-08-08"},
    {"id":9,"topic":"Familiennachzug","statement":"Der Bundestag beschloss am 27.06.2025 die zweijährige Aussetzung des Familiennachzugs zu subsidiär Schutzberechtigten mit 444 Ja- und 133 Nein-Stimmen; Härtefälle bleiben möglich.","value":"444 zu 133","scope":"§ 36a/Übergangsregelung, subsidiär Schutzberechtigte","source_name":"Deutscher Bundestag – Gesetzesbeschluss und namentliche Abstimmung","source_url":"https://www.bundestag.de/dokumente/textarchiv/2025/kw23-de-familiennachzug-1083664","limitations":"Betrifft nicht pauschal den Familiennachzug aller anerkannten Flüchtlinge; die praktische Härtefallanwendung ist separat zu untersuchen.","checked_at":"2026-08-08"},
    {"id":10,"topic":"Familiennachzug","statement":"Vor der Aussetzung war der Nachzug für diese Gruppe bereits auf 1.000 Visa pro Monat begrenzt; Regierungsziel war die Entlastung der Aufnahme- und Integrationssysteme.","value":"maximal 1.000 Visa/Monat zuvor","scope":"subsidiär Schutzberechtigte","source_name":"Deutscher Bundestag – hib 201/2025","source_url":"https://www.bundestag.de/presse/hib/kurzmeldungen-1084498","limitations":"Die gesetzgeberische Zielbehauptung beweist nicht automatisch die tatsächliche Entlastungswirkung; Integrations- und Familienfolgen sind Gegenfragen.","checked_at":"2026-08-08"},
    {"id":11,"topic":"Hans-Bunte-Fall Freiburg","statement":"Sieben Angeklagte wurden wegen Vergewaltigung, einer wegen sexuellen Übergriffs und zwei wegen unterlassener Hilfeleistung verurteilt; ein weiterer wurde vom Vergewaltigungsvorwurf freigesprochen und wegen eines Drogendelikts verurteilt.","value":"11 Angeklagte, 10 mit Verurteilung","scope":"LG Freiburg, Urteil vom 23.07.2020","source_name":"Landgericht Freiburg – Urteilsmitteilung","source_url":"https://landgericht-freiburg.justiz-bw.de/pb/,Lde/6490559/?LISTPAGE=5684243","limitations":"Nicht jeder Angeklagte wurde wegen Vergewaltigung verurteilt. Strafhöhe und Delikt müssen individuell zugeordnet werden.","checked_at":"2026-08-08"},
    {"id":12,"topic":"Hans-Bunte-Fall Freiburg","statement":"Der Bundesgerichtshof verwarf die Revisionen; das Urteil des Landgerichts wurde 2021 rechtskräftig.","value":"BGH 1 StR 81/21","scope":"Revisionen von fünf Angeklagten","source_name":"Bundesgerichtshof – Pressemitteilung 115/2021","source_url":"https://juris.bundesgerichtshof.de/cgi-bin/rechtsprechung/document.py?Art=pm&Datum=2021-6&Gericht=bgh&anz=18&nr=119557&pos=4","limitations":"Die Revisionsentscheidung prüft Rechtsfehler und ist keine neue Tatsachenverhandlung.","checked_at":"2026-08-08"},
    {"id":13,"topic":"Hans-Bunte-Fall Freiburg","statement":"Ein vierjähriges Einreise- und Aufenthaltsverbot gegen einen irakischen, rechtskräftig wegen Vergewaltigung verurteilten Täter wurde im Januar 2025 gerichtlich gebilligt.","value":"VG Freiburg 8 K 835/24","scope":"konkreter irakischer Täter, generalpräventives Einreiseverbot","source_name":"Verwaltungsgericht Freiburg","source_url":"https://verwaltungsgericht-freiburg.justiz-bw.de/pb/,Lde/Startseite/Presse/Weiteres+Urteil+im+_Hans+Bunte-Fall_+Vierjaehriges+Einreise-+und+Aufenthaltsverbot+fuer+einen+der+Taeter+gerichtlich+gebilligt","limitations":"Keine Aussage über Aufenthaltsstatus oder Abschiebbarkeit aller übrigen Verurteilten.","checked_at":"2026-08-08"},
    {"id":14,"topic":"Velbert-Gruppenvergewaltigung","statement":"Sechs bulgarische Jugendliche wurden 2018 verurteilt: drei wegen Vergewaltigung, drei wegen Beihilfe; das Strafmaß reichte bis vier Jahre und neun Monate Jugendhaft, zwei Beihilfestrafen wurden zur Bewährung ausgesetzt.","value":"6 Verurteilte im ersten Verfahren","scope":"LG Wuppertal, nichtöffentlicher Jugendstrafprozess","source_name":"Landgericht Wuppertal – berichtigte Pressemitteilung 16/2018","source_url":"https://www.lg-wuppertal.nrw.de/behoerde/presse/archiv/2018/Pressemitteilung-16-2018-berichtigt.pdf","limitations":"Zwei weitere mutmaßlich Beteiligte waren nicht Gegenstand dieses ersten Urteils. Jugendstrafverfahren begrenzen öffentliche Detailinformationen.","checked_at":"2026-08-08"},
    {"id":15,"topic":"Nürnberg EKO Kajal","statement":"Die Nürnberger Polizei gründete am 18.05.2026 die EKO Kajal, nachdem zehn Personen identifiziert worden waren und gegen vier unter anderem wegen Drogenabgabe an Minderjährige und Sexualdelikten ermittelt wurde.","value":"10 identifiziert; zunächst 4 Beschuldigte im Deliktskomplex","scope":"polizeilicher Ermittlungsstand vom 21.05.2026","source_name":"Polizeipräsidium Mittelfranken – Meldung 492","source_url":"https://www.polizei.bayern.de/aktuelles/pressemitteilungen/103066/index.html","limitations":"Tatverdacht, keine gerichtliche Tatsachenfeststellung. Die Meldung belegt nicht, dass alle Identifizierten Teil einer hierarchisch organisierten Gruppe sind.","checked_at":"2026-08-08"},
    {"id":16,"topic":"Nürnberg EKO Kajal","statement":"Am 07.07.2026 befanden sich laut Polizei zehn Tatverdächtige aus dem EKO-Kajal-Komplex in Untersuchungshaft; zuletzt wurden zwei syrische Staatsangehörige wegen Vergewaltigungs- und Drogendeliktsverdachts inhaftiert.","value":"10 Tatverdächtige in Untersuchungshaft","scope":"polizeilicher Ermittlungsstand vom 07.07.2026","source_name":"Polizeipräsidium Mittelfranken – Meldung 628","source_url":"https://www.polizei.bayern.de/aktuelles/pressemitteilungen/105449/index.html","limitations":"Haftbefehl setzt dringenden Tatverdacht und einen Haftgrund voraus, ist aber keine Verurteilung. Nationalitäten einzelner Verdächtiger erlauben keine Aussage über Bevölkerungsgruppen.","checked_at":"2026-08-08"},
    {"id":17,"topic":"Migrationsstatistik","statement":"Die Nettozuwanderung nach Deutschland sank 2025 gegenüber 2024 um 45 Prozent auf rund 235.000 Personen; gegenüber EU-Staaten bestand ein negativer Wanderungssaldo von 54.000.","value":"235.000 netto; −45 % zum Vorjahr","scope":"Deutschland, endgültige Wanderungsstatistik 2025","source_name":"Statistisches Bundesamt – Pressemitteilung 184/2026","source_url":"https://www.destatis.de/DE/Presse/Pressemitteilungen/2026/06/PD26_184_12411.html","limitations":"Nettozuwanderung umfasst alle registrierten Zu- und Fortzüge und ist nicht mit Asylanträgen oder der Zahl Schutzsuchender gleichzusetzen. Sie erklärt keine politische Ursache allein.","checked_at":"2026-08-08"},
    {"id":18,"topic":"Deutsche Grenzzurückweisungen","statement":"Die Bundesregierung meldete für den 1. Januar bis 30. April 2025 insgesamt 12.481 angeordnete Zurückweisungen an allen deutschen Grenzen; vom 7. bis 25. Mai kamen an den Landgrenzen 2.188 Zurückweisungen hinzu.","value":"12.481 bis 30.04.; 2.188 vom 07.–25.05.2025","scope":"polizeiliche Eingangsstatistik; alle Zurückweisungsgründe, nicht nur Asylgesuche","source_name":"Deutscher Bundestag – hib 270/2025, Antwort 21/625","source_url":"https://www.bundestag.de/presse/hib/kurzmeldungen-1097834","limitations":"Angeordnete Zurückweisungen, vollzogene Zurückweisungen, Zurückschiebungen und Zurückweisungen von Schutzsuchenden sind verschiedene Kategorien. Eine Gesamtzahl darf nicht pauschal als Zahl abgewiesener Asylsuchender bezeichnet werden.","checked_at":"2026-08-08"},
    {"id":19,"topic":"Bezahlkarte","statement":"Der Landkreis Lörrach dokumentierte die Einführung der Bezahlkarte in einer öffentlichen Mitteilungsvorlage 232/2025 für den Sozialausschuss vom 1. Oktober 2025.","value":"amtlicher Sachstandsbericht 232/2025","scope":"Landkreis Lörrach; lokale Umsetzung, keine bundesweite Wirkungsstudie","source_name":"Landkreis Lörrach – öffentliche Mitteilungsvorlage","source_url":"https://session.loerrach-landkreis.de/data/buergerinfo/getfile.asp?id=76535&type=do","limitations":"Ein Umsetzungsbericht kann Ausgabezahlen und Verwaltungsabläufe belegen, aber nicht allein eine migrationssteuernde Wirkung oder Überweisungen an Schleuser messen.","checked_at":"2026-08-08"},
    {"id":20,"topic":"Einbürgerung","statement":"Die Stadt Freiburg stellte im November 2025 auf regelmäßige Feiern um, bei denen die Einbürgerung und Übergabe der Urkunde unmittelbar während des Festakts erfolgen.","value":"neues Format seit 14.11.2025","scope":"Stadt Freiburg, nicht Landkreis Breisgau-Hochschwarzwald","source_name":"Stadt Freiburg – Einbürgerungsfeiern im neuen Format","source_url":"https://www.freiburg.de/pb/2482196.html","limitations":"Das Veranstaltungsformat sagt nichts über materielle Einbürgerungsvoraussetzungen, Ablehnungsquote oder durchschnittliche Verfahrensdauer aus. Stadt- und Landkreiszahlen dürfen nicht vermischt werden.","checked_at":"2026-08-08"},
    {"id":21,"topic":"Einbürgerung","statement":"Im Jahr 2025 wurden nach vorläufigen Ergebnissen 332.500 Menschen eingebürgert, 14 Prozent mehr als 2024; 1.500 Einbürgerungen erfolgten noch über die verkürzte Frist für besondere Integrationsleistungen.","value":"332.500; +14 %","scope":"Deutschland, Einbürgerungsstatistik 2025","source_name":"Statistisches Bundesamt – Pressemitteilung 186/2026","source_url":"https://www.destatis.de/DE/Presse/Pressemitteilungen/2026/06/PD26_186_125.html","limitations":"Einbürgerungszahl ist weder Zuwanderungszahl noch Zahl neu entstandener Einwohner. Eingebürgerte leben regelmäßig bereits seit Jahren in Deutschland; spätere PKS führt sie als deutsche Staatsangehörige.","checked_at":"2026-08-08"},
    {"id":22,"topic":"Syrien Rückkehr","statement":"UNHCR meldete Ende Januar 2025 rund 200.000 Rückkehrende nach Syrien seit dem Sturz Assads; die Zahl bezog sich überwiegend auf Flüchtlinge in Nachbarstaaten und war eine Schätzung.","value":"rund 200.000 seit Dezember 2024","scope":"grenzüberschreitende Rückkehr nach Syrien, nicht speziell aus Deutschland","source_name":"UNHCR – Pressemitteilung vom 27.01.2025","source_url":"https://www.unhcr.org/news/press-releases/unhcr-s-grandi-calls-global-action-support-syrians-returning-home","limitations":"Rückkehr aus Türkei, Libanon, Jordanien oder Irak beweist weder individuelle Sicherheit noch Zumutbarkeit einer Abschiebung aus Deutschland. Zeitpunkt und Bezugsgruppe müssen mitgenannt werden.","checked_at":"2026-08-08"},
    {"id":23,"topic":"GEAS","statement":"Der EU-Migrations- und Asylpakt wurde am 14. Mai 2024 vom Rat angenommen und ist seit 12. Juni 2026 anwendbar.","value":"anwendbar seit 12.06.2026","scope":"EU-Pakt als Regelungspaket; nationale Umsetzung und Wirkung separat","source_name":"Rat der Europäischen Union – Pact on migration and asylum","source_url":"https://www.consilium.europa.eu/en/policies/eu-pact-migration-asylum/","limitations":"Das Inkrafttreten belegt noch nicht, dass Außengrenzverfahren, Solidaritätsmechanismus oder Rückführungen praktisch wie vorgesehen funktionieren.","checked_at":"2026-08-08"},
    {"id":24,"topic":"Migrationsstatistik","statement":"Das BAMF registrierte 2025 insgesamt 168.543 Asylanträge, davon 113.236 Erst- und 55.307 Folgeanträge; die Erstanträge sanken gegenüber 2024 um 50,7 Prozent.","value":"168.543 insgesamt; 113.236 Erstanträge","scope":"Deutschland, BAMF-Geschäftsstatistik Gesamtjahr 2025","source_name":"BAMF – Asylzahlen Gesamtjahr 2025","source_url":"https://www.bamf.de/SharedDocs/Meldungen/DE/2026/260112-asylzahlen-dezember-und-gesamtjahr-2025.html","limitations":"Erst- und Folgeanträge müssen getrennt ausgewiesen werden. 17.707 Erstanträge betrafen in Deutschland geborene Kinder unter einem Jahr; Anträge sind weder Grenzübertritte noch Nettozuwanderung.","checked_at":"2026-08-08"},
    {"id":25,"topic":"Afghanistan-Aufnahmeprogramme","statement":"Nach Bundestagsangaben waren seit Mitte August 2025 mindestens 450 Afghanen mit deutscher Aufnahmezusage in Pakistan inhaftiert und 211 nach Afghanistan abgeschoben worden.","value":"mindestens 450 inhaftiert; 211 abgeschoben","scope":"Stand der parlamentarischen Dokumentation Ende 2025","source_name":"Deutscher Bundestag – Vorgang Aufnahmezusagen einhalten","source_url":"https://www.bundestag.de/parlament/plenum/abstimmung/abstimmung?id=981","limitations":"Die Zahl stammt im parlamentarischen Vorgang aus einem Oppositionsantrag und ist von späteren Regierungsantworten und Stichtagen zu unterscheiden. Aufnahmezusage, Visum und abgeschlossene Sicherheitsprüfung sind verschiedene Stufen.","checked_at":"2026-08-08"},
    {"id":26,"topic":"Einbürgerung","statement":"Destatis veröffentlichte für 2025 vorläufig 332.524 Einbürgerungen; eine vor Veröffentlichung der amtlichen Statistik berichtete Medienschätzung von mehr als 309.000 war damit zu niedrig.","value":"332.524","scope":"Deutschland, Berichtsjahr 2025; amtlicher Stand 03.06.2026","source_name":"Statistisches Bundesamt – Einbürgerungen und ausgeschöpftes Einbürgerungspotential","source_url":"https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bevoelkerung/Migration-Integration/Tabellen/einbuergerungen-einbuergerungsquote-lr.html","limitations":"Eine vor dem 3. Juni 2026 klar als Recherche oder Schätzung gekennzeichnete Zahl darf nicht rückwirkend wie eine trotz besseren Wissens verbreitete Falschangabe bewertet werden.","checked_at":"2026-08-08"},
    {"id":27,"topic":"Afghanistan-Aufnahmeprogramme","statement":"Der EuGH entschied am 04.10.2024, dass die kumulativen diskriminierenden Maßnahmen des Taliban-Regimes gegen Frauen Verfolgung darstellen; bei der individuellen Prüfung darf ein Mitgliedstaat Geschlecht und afghanische Staatsangehörigkeit allein berücksichtigen.","value":"EuGH C-608/22 und C-609/22","scope":"Flüchtlingsstatus afghanischer Frauen; unionsrechtliche Auslegung","source_name":"Gerichtshof der Europäischen Union – Urteil in verbundenen Rechtssachen C-608/22 und C-609/22","source_url":"https://infocuria.curia.europa.eu/tabs/redirect/juris/liste.jsf?num=C-608%2F22","limitations":"Das Urteil betrifft afghanische Frauen und erlaubt eine bestimmte Form der individuellen Prüfung; es gewährt nicht jedem afghanischen Staatsangehörigen automatisch Schutz und sagt nichts über Aufnahmeprogramme außerhalb des Asylverfahrens.","checked_at":"2026-08-08"},
    {"id":28,"topic":"Familiennachzug","statement":"Die seit 24.07.2025 geltende Aussetzung betrifft den Familiennachzug zu subsidiär Schutzberechtigten bis einschließlich 23.07.2027; Härtefälle bleiben möglich.","value":"24.07.2025 bis 23.07.2027","scope":"subsidiär Schutzberechtigte, nicht sämtliche Visa zum Familiennachzug","source_name":"Auswärtiges Amt – Information zur Aussetzung des Familiennachzugs","source_url":"https://www.auswaertiges-amt.de/de/2727950-2727950","limitations":"Gesamtzahlen nationaler Visa zum Familiennachzug umfassen zahlreiche andere Rechts- und Personengruppen. Erteilte Visa sind zudem nicht in jedem Fall identisch mit im selben Zeitraum vollzogenen Einreisen.","checked_at":"2026-08-08"},
]

OMISSION_EXAMPLES = [
    {"id":1,"pattern":"Artikel nennt bei einem Tatverdächtigen keine Nationalität.","verdict":"nicht automatisch eine Auslassung","explanation":"Zuerst prüfen, ob Polizei, Staatsanwaltschaft oder Gericht die Staatsangehörigkeit veröffentlicht haben und ob sie für den berichteten Sachverhalt relevant ist.","required_evidence":"Primärmitteilung mit Nationalität, Veröffentlichungszeitpunkt und begründete Relevanz."},
    {"id":2,"pattern":"Artikel nennt einen Tatverdächtigen 'deutsch', aber keine Einbürgerung oder Familienmigration.","verdict":"meist nicht prüfbar","explanation":"Deutsch bezeichnet die Staatsangehörigkeit. Ein möglicher Migrationshintergrund ist in der PKS und häufig auch in Ermittlungsmitteilungen nicht vorhanden.","required_evidence":"Belastbare Primärquelle, keine Namens- oder Herkunftsvermutung."},
    {"id":3,"pattern":"Artikel diskutiert Kriminalität einer Nationalität, nennt aber nur absolute Tatverdächtigenzahlen.","verdict":"relevanter statistischer Kontext fehlt","explanation":"Ohne passende Bevölkerungsbasis, Alters-/Geschlechtsstruktur und Ausschluss nichtansässiger Personen kann Überrepräsentation falsch berechnet werden.","required_evidence":"PKS-Tabelle, kompatible Bevölkerungsstatistik und dokumentierte Berechnung."},
    {"id":4,"pattern":"Artikel erklärt eine Gruppenabweichung ausschließlich mit Herkunft oder ausschließlich mit Sozialstruktur.","verdict":"einseitige Kausaldeutung","explanation":"Eine deskriptive Statistik beweist keine einzelne Ursache. Mehrere konkurrierende Erklärungen und Studienlage gehören in die Prüfung.","required_evidence":"Multivariate Forschung, Definitionen und Gegenhypothesen."},
]
